---
abstract: 'Parse/Analyse XML-Files created by DBDesigner 4 (FabForce)'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires:
  XML::Twig   : 3.32
  XML::Writer : 0.6
  IO::File    : 1.1
  Carp        : 1.04
  Exporter    : 5.58
generated_by: 'h2xs version 1.23'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
name: FabForce-DBDesigner4
provides:
  FabForce::DBDesigner4:
    file: /lib/FabForce/DBDesigner4.pm
    version: 0.304
  FabForce::DBDesigner4::SQL:
    file: /lib/FabForce/DBDesigner4/SQL.pm
    version: 0.7
  FabForce::DBDesigner4::Table:
    file: /lib/FabForce/DBDesigner4/Table.pm
    version: 0.05
  FabForce::DBDesigner4::XML:
    file: /lib/FabForce/DBDesigner4/XML.pm
    version: 0.1
  FabForce::DBDesigner4::SQL::Mysql:
    file: /lib/FabForce/DBDesigner4/SQL/Mysql.pm
    version: 0.02
  FabForce::DBDesigner4::SQL::Utils:
    file: /lib/FabForce/DBDesigner4/SQL/Utils.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses
version: 0.304

